//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Machine_Test___Clavax.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Machine_Test___ClavaxDBEntities : DbContext
    {
        public Machine_Test___ClavaxDBEntities()
            : base("name=Machine_Test___ClavaxDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Employee_Registration> Employee_Registration { get; set; }
        public virtual DbSet<State_Master> State_Master { get; set; }
        public virtual DbSet<Employee_Hobby> Employee_Hobby { get; set; }
        public virtual DbSet<Hobby_Master> Hobby_Master { get; set; }
    }
}
