//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Machine_Test___Clavax.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_Hobby
    {
        public int emp_hobby_id { get; set; }
        public Nullable<int> hobby_fid { get; set; }
        public Nullable<int> emp_fid { get; set; }
    
        public virtual Employee_Registration Employee_Registration { get; set; }
        public virtual Hobby_Master Hobby_Master { get; set; }
    }
}
