//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Machine_Test___Clavax.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_Registration
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee_Registration()
        {
            this.Employee_Hobby = new HashSet<Employee_Hobby>();
        }
    
        public int Employee_ID { get; set; }
        public string Employee_Name { get; set; }
        public Nullable<System.DateTime> Employee_DOB { get; set; }
        public string Gender { get; set; }
        public string Address { get; set; }
        public Nullable<int> State_fid { get; set; }
        public string Hobbies { get; set; }
    
        public virtual State_Master State_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee_Hobby> Employee_Hobby { get; set; }
    }
}
