//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Machine_Test___Clavax.DB
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Hobby_Master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hobby_Master()
        {
            this.Employee_Hobby = new HashSet<Employee_Hobby>();
        }
    
        public int hobbyID { get; set; }
        [Required]
        [Display(Name = "Hobby")]
        public string hobbyName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee_Hobby> Employee_Hobby { get; set; }
        public virtual Hobby_Master Hobby_Master1 { get; set; }
        public virtual Hobby_Master Hobby_Master2 { get; set; }
    }
}
